const sampleListings = [
  {
    title: "Cozy Cottage in Manali",
    description:
      "Nestled in the hills with a serene view of the Beas River. Perfect for a peaceful getaway.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Manali",
    country: "India",
  },
  {
    title: "Beachfront Bungalow in Goa",
    description:
      "Wake up to the sound of waves. A beautiful private bungalow right on Calangute beach.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Calangute, Goa",
    country: "India",
  },
  {
    title: "Urban Apartment in Hyderabad",
    description:
      "Modern living in the heart of the city. Close to major tech parks and shopping malls.",
    image: "https://images.unsplash.com/photo-1598928506311-5c1f1b6e3f6d?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Mountain Retreat in Leh",
    description:
      "Experience tranquility at this high-altitude retreat with breathtaking views of the Himalayas.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Leh",
    country: "India",
  },
  {
    title: "Luxury Villa in Udaipur",
    description:
      "Spacious and elegant villa with a private pool, overlooking Lake Pichola.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 5500,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Historic Haveli in Jaipur",
    description:
      "Live like royalty in this restored haveli in the heart of the Pink City.",
    image: "https://images.unsplash.com/photo-1593696140826-c58b02198d4a?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Kerala Backwaters Houseboat",
    description:
      "A unique experience floating on the serene backwaters of Alleppey.",
    image: "https://images.unsplash.com/photo-1598142398242-07f160682247?auto=format&fit=crop&w=800&q=60",
    price: 6000,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Chic Studio in Mumbai",
    description:
      "A stylish and compact studio in the bustling neighborhood of Bandra.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Riverside Camp in Rishikesh",
    description:
      "Adventure awaits at this campsite by the Ganges. Ideal for rafting and yoga.",
    image: "https://images.unsplash.com/photo-1571863533956-01c88e79957e?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Tea Plantation Bungalow in Munnar",
    description:
      "Stay amidst lush green tea gardens and enjoy the fresh mountain air.",
    image: "https://images.unsplash.com/photo-1549492423-400259a5e3a5?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Colonial Charm in Shimla",
    description: "A beautiful colonial-era cottage offering panoramic valley views.",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Desert Oasis Tent in Jaisalmer",
    description: "Experience the Thar Desert with a luxurious tent stay under the stars.",
    image: "https://images.unsplash.com/photo-1587352344281-339d14c18097?auto=format&fit=crop&w=800&q=60",
    price: 4500,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Modern Loft in Bengaluru",
    description: "A trendy loft in Indiranagar, close to the best pubs and restaurants.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=60",
    price: 3200,
    location: "Bengaluru",
    country: "India",
  },
  {
    title: "French Quarter Home in Pondicherry",
    description: "Charming and colorful house in the heart of the White Town.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=60",
    price: 2600,
    location: "Pondicherry",
    country: "India",
  },
  {
    title: "Artist's Den in Kolkata",
    description: "A quirky and artistic space reflecting the culture of the City of Joy.",
    image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Kolkata",
    country: "India",
  },
  {
    title: "Treehouse in Wayanad",
    description: "Live among the trees in this unique and eco-friendly treehouse.",
    image: "https://images.unsplash.com/photo-1552607676-17f08034b6ce?auto=format&fit=crop&w=800&q=60",
    price: 3800,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Royal Suite near Taj Mahal",
    description: "Enjoy views of the Taj Mahal from this luxurious and opulent suite.",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=60",
    price: 7000,
    location: "Agra",
    country: "India",
  },
  {
    title: "Peaceful Farmstay in Punjab",
    description: "Experience authentic Punjabi hospitality and culture at this farmstay.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Amritsar",
    country: "India",
  },
  {
    title: "Ganges View Apartment in Varanasi",
    description: "A simple, clean apartment with a balcony overlooking the sacred Ghats.",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=60",
    price: 1300,
    location: "Varanasi",
    country: "India",
  },
  {
    title: "Himalayan Homestay in Darjeeling",
    description: "Cozy homestay with stunning views of Kanchenjunga.",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=60",
    price: 1600,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Luxe Penthouse in Delhi",
    description: "A luxurious penthouse in South Delhi with a private terrace.",
    image: "https://images.unsplash.com/photo-1628592102751-ba83b0314276?auto=format&fit=crop&w=800&q=60",
    price: 6500,
    location: "New Delhi",
    country: "India",
  },
  {
    title: "Coffee Estate Homestay in Coorg",
    description: "Wake up to the aroma of coffee in this beautiful estate.",
    image: "https://images.unsplash.com/photo-1598928506311-5c1f1b6e3f6d?auto=format&fit=crop&w=800&q=60",
    price: 2400,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Secluded Beach Hut in Gokarna",
    description: "A rustic and charming hut on a quiet, pristine beach.",
    image: "https://images.unsplash.com/photo-1573843981267-be199c65a7a4?auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Gokarna",
    country: "India",
  },
  {
    title: "Vineyard Villa in Nashik",
    description: "Stay at a villa surrounded by vineyards, with wine tasting tours available.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=60",
    price: 4200,
    location: "Nashik",
    country: "India",
  },
  {
    title: "Heritage Hotel in Mysore",
    description: "Experience the grandeur of Mysore in this elegant heritage property.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "Mysore",
    country: "India",
  },
  {
    title: "Bohemian Flat in Pune",
    description: "A vibrant and artsy flat in the youthful area of Koregaon Park.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    price: 2100,
    location: "Pune",
    country: "India",
  },
  {
    title: "Cabin in the Woods in Ooty",
    description: "A cozy wooden cabin surrounded by pine forests. Perfect for nature lovers.",
    image: "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Ooty",
    country: "India",
  },
  {
    title: "Andaman Sea Villa",
    description: "Private villa with direct access to a white sand beach in Havelock.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=60",
    price: 8000,
    location: "Havelock Island",
    country: "India",
  },
  {
    title: "Spiritual Ashram Stay in Rishikesh",
    description: "A simple and clean room in an ashram with yoga and meditation classes.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Lakefront Cottage in Nainital",
    description: "Charming cottage with a beautiful view of Naini Lake.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2e0?auto=format&fit=crop&w=800&q=60",
    price: 2300,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Modern Apartment in Chennai",
    description: "A well-equipped modern apartment in a central, convenient location.",
    image: "https://images.unsplash.com/photo-1560185007-c5ca936a4232?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Luxury Tent in Ranthambore",
    description: "Glamping near the national park. Ideal for wildlife enthusiasts.",
    image: "https://images.unsplash.com/photo-1613553429205-2425667a42b0?auto=format&fit=crop&w=800&q=60",
    price: 5200,
    location: "Ranthambore",
    country: "India",
  },
  {
    title: "Blue City View Homestay in Jodhpur",
    description: "Stay in a traditional home with rooftop views of Mehrangarh Fort.",
    image: "https://images.unsplash.com/photo-1541123356219-2849c37c2251?auto=format&fit=crop&w=800&q=60",
    price: 1400,
    location: "Jodhpur",
    country: "India",
  },
  {
    title: "Quiet Retreat in Kasauli",
    description: "A peaceful cottage away from the crowds, perfect for relaxation.",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Kasauli",
    country: "India",
  },
  {
    title: "Sea View Apartment in Visakhapatnam",
    description: "Modern apartment with a stunning view of the Bay of Bengal.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Visakhapatnam",
    country: "India",
  },
  {
    title: "Eco-Lodge in the Sunderbans",
    description: "Stay in a sustainable lodge and explore the mangrove forests.",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
    price: 3300,
    location: "Sunderbans",
    country: "India",
  },
  {
    title: "Rock Climber's Pad in Hampi",
    description: "Basic but comfortable stay for climbers and backpackers exploring Hampi's boulders.",
    image: "https://images.unsplash.com/photo-1599696849488-4b95d523a10f?auto=format&fit=crop&w=800&q=60",
    price: 700,
    location: "Hampi",
    country: "India",
  },
  {
    title: "Garden Villa in Lonavala",
    description: "A spacious villa with a private garden, ideal for family weekends.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2e0?auto=format&fit=crop&w=800&q=60",
    price: 4800,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Orchard Farmstay in Himachal",
    description: "Stay in a working apple orchard and enjoy fresh, organic food.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 2100,
    location: "Kotgarh",
    country: "India",
  },
  {
    title: "Dune-View Room in Pushkar",
    description: "A room with a view of the desert dunes, close to the famous Brahma Temple.",
    image: "https://images.unsplash.com/photo-1598928506311-5c1f1b6e3f6d?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Pushkar",
    country: "India",
  },
  {
    title: "Mountain Lodge in Auli",
    description: "Perfect for skiing enthusiasts, this lodge offers stunning Himalayan views.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 3600,
    location: "Auli",
    country: "India",
  },
  {
    title: "Fisherman's Cove in Kovalam",
    description: "A quaint and simple stay in a fishing village, offering an authentic experience.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=60",
    price: 1100,
    location: "Kovalam",
    country: "India",
  },
  {
    title: "Historic Fort Stay in Alwar",
    description: "Experience history firsthand by staying in a beautifully restored fort.",
    image: "https://images.unsplash.com/photo-1593696140826-c58b02198d4a?auto=format&fit=crop&w=800&q=60",
    price: 6000,
    location: "Alwar",
    country: "India",
  },
  {
    title: "Valley View Cottage in Mussoorie",
    description: "A charming cottage overlooking the Doon Valley. Perfect for a writer's retreat.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Mussoorie",
    country: "India",
  },
  {
    title: "Riverside Cabin in Tirthan Valley",
    description: "A rustic wooden cabin by the Tirthan river, ideal for angling and trekking.",
    image: "https://images.unsplash.com/photo-1552607676-17f08034b6ce?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Tirthan Valley",
    country: "India",
  },
  {
    title: "Luxury Beach Resort in Mahabalipuram",
    description: "Indulge in luxury with a private beach, spa, and fine dining.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=60",
    price: 9000,
    location: "Mahabalipuram",
    country: "India",
  },
  {
    title: "Monastery View Guesthouse in Dharamshala",
    description: "A simple guesthouse offering stunning views of the Dalai Lama Temple complex.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Mcleodganj",
    country: "India",
  },
  {
    title: "Urban Oasis in Ahmedabad",
    description: "A peaceful and green property in the midst of a bustling city.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Ahmedabad",
    country: "India",
  },
  {
    title: "Kashmiri Houseboat on Dal Lake",
    description: "A traditional, intricately carved houseboat for a unique Srinagar experience.",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=60",
    price: 4500,
    location: "Srinagar",
    country: "India",
  },
  {
    title: "Surfer's Shack in Varkala",
    description: "Basic accommodation right on the cliff, perfect for surfers and backpackers.",
    image: "https://images.unsplash.com/photo-1573843981267-be199c65a7a4?auto=format&fit=crop&w=800&q=60",
    price: 850,
    location: "Varkala",
    country: "India",
  },
  {
    title: "Bamboo Cottage in Shillong",
    description: "Eco-friendly cottage made of bamboo, offering a taste of Khasi life.",
    image: "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Shillong",
    country: "India",
  },
];

module.exports = { data: sampleListings };